apps/core/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.core.views import *
app_name='core'
urlpatterns=[
	
	path('calendario/', EncuentroCalendario.as_view(),name='encuentros_calendario'),
	path('api/encuentros/',EncuentroAPI.as_view(),name='api-encuentro'),

]

apps/landing/urls.py
from django.urls import path, include
from apps.landing.views import Index, club_info
app_name='landing'
urlpatterns=[
	path('', Index.as_view(), name='index'),
	path('club', club_info, name='club_info'),
]

soccer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('admin/core/', include('apps.core.urls',namespace='apps-core')),
    path('', include('apps.landing.urls',namespace='apps-landing-page')),
]

apps/core/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.functional import cached_property
from django.contrib.auth.models import User
# Create your models here.

class Imagen(models.Model):
	"""docstring for imagen"""
	imagen = models.ImageField(
        upload_to='static/images/',
        null=True,
        blank=True,
        verbose_name='Img'
    )
	def __str__(self):
		return f'{self.imagen}'
# para las personas
class Rol(models.Model):
	"""docstring for Rol"""
	rol=models.CharField(max_length=50,choices=(
				('En','Entrenador'),
				('Dir','Director'),
				('Coo','Coordinador'),
				('At','Atleta'),
			)
		)
	def __str__(self):
		return self.rol
# para los pos
class Tipo(models.Model):
	"""docstring for Tipo"""
	name=models.CharField(max_length=50)
	def __str__(self):
		return self.nombre

class Estado(models.Model):
	"""docstring for Estado"""
	name=models.CharField(max_length=50)
	def __str__(self):
		return self.name

class Municipio(models.Model):
	"""docstring for Municipio"""
	name=models.CharField(max_length=50)
	estado=models.ForeignKey(Estado,null=True,blank=True,on_delete=models.CASCADE)
	def __str__(self):
		return '{} - {}'.format(self.name, self.estado)

class Estadio(models.Model):
	nombre=models.CharField(max_length=50)
	direccion=models.ForeignKey(Municipio,null=True,blank=True,on_delete=models.CASCADE)
	def __str__(self):
		return self.nombre

class Red(models.Model):
	"""docstring for Redes"""
	facebook=models.CharField(max_length=50)
	twiter=models.CharField(max_length=50)
	instagram=models.CharField(max_length=50)
	def __str__(self):
		return self.facebook

class Persona(models.Model):
	"""docstring for Persona"""
	imagen = models.ImageField(
        upload_to='static/images/directivo',
        null=True,
        blank=True,
        verbose_name='Img'
    )
	nombre=models.CharField(max_length=50)
	apellido=models.CharField(max_length=50)
	cedula=models.IntegerField(unique=True)
	email=models.EmailField()
	edad=models.IntegerField(null=True)
	peso=models.IntegerField(null=True)
	red=models.ForeignKey(Red,null=True,blank=True,on_delete=models.CASCADE)
	rol=models.ForeignKey(Rol,null=True,blank=True,on_delete=models.CASCADE)
	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellido)

class Club(models.Model):
	"""docstring for Club"""
	# imagen=models.ForeignKey(Imagen,null=True,blank=True,on_delete=models.CASCADE)
	nombre=models.CharField(max_length=50)
	# datos random
	mision=models.TextField(null=True,default='')
	historia=models.TextField(null=True,default='')
	directivo=models.ManyToManyField(Persona,blank=True)
	estadio=models.ForeignKey(Estadio,null=True,blank=True,on_delete=models.CASCADE)
	email=models.EmailField(default='xxxxx@xxx.com')
	red=models.ForeignKey(Red,null=True,blank=True,on_delete=models.CASCADE)
	numero_telefono=models.CharField(max_length=50,default='')
	direccion=models.ForeignKey(Municipio,null=True,blank=True,on_delete=models.CASCADE)
	creado=models.DateTimeField(auto_now_add=True)
	actualizado=models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.nombre

class Divicion(models.Model):
	"""docstring for Divicion"""
	name=models.CharField(max_length=50,choices=(
		('sub','12'),
		('sub','14'),
		('sub','16'),
		('sub','18'),
		('sub','21'),
		)
	)
	def __str__(self):
		return self.name

class Parrilla(models.Model):
	"""docstring for Parrilla"""
	persona=models.ForeignKey(Persona,null=True,blank=True,on_delete=models.CASCADE)
	divicion=models.ForeignKey(
		Divicion,
		null=True,
		blank=True,
		on_delete=models.CASCADE,
	) 
	def __str__(self):
		return self.persona

class Encuentro(models.Model):
	"""docstring for Encuentro"""
	nombre=models.CharField(max_length=50)
	tipo_de_encuentro=models.CharField(max_length=50,choices=(
		('A','Amistoso'),
		('C','Clasificatorio'),
		('E','Estadal'),
		('N','Nacional'),
		)
	)
	divicion=models.ForeignKey(Divicion,null=True,blank=True,on_delete=models.CASCADE)
	equipo_casa=models.ForeignKey(Club,related_name='casa',null=True,blank=True,on_delete=models.CASCADE)
	equipo_invitado=models.ForeignKey(Club,related_name='invitado',null=True,blank=True,on_delete=models.CASCADE)
	goles_invitado=models.IntegerField(default=0)
	goles_casa=models.IntegerField(default=0)
	creado=models.DateTimeField(auto_now_add=True)
	actualizado=models.DateTimeField(auto_now=True)
	estatus=models.CharField(max_length=50,choices=(
			('1','Pendiente'),
			('1','Finalizado'),
		), default='Pe'
	)
	def __str__(self):
		return f'Encuentro:{self.nombre}'













# esto es para el landing
class Post(models.Model):
	"""docstring for Post"""
	title=models.CharField(max_length=50)
	content=models.TextField()
	date_create=models.DateField()
	tipo=models.ForeignKey(Tipo,null=True,blank=True,on_delete=models.CASCADE)
	imagen=models.ManyToManyField(Imagen,blank=True)
	def __str__(self):
		return self.title

apps/landing/models.py
from django.db import models

# Create your models here.

apps/user/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, View
from apps.core.form import PostForm
from apps.core.models import *


# Create your views here.

def Show(request,id_post):
	post=Post.objects.get(id=id_post)
	context={'post':post}
	return render(request,'post/show.html',context)

class List(ListView):
	"""docstring for MascotaList"""
	model=Post
	template_name='post/list.html'

class Create(CreateView):
	"""docstring for MascotaCreate"""
	model=Post
	form_class=PostForm
	template_name='post/view.html'
	success_url=reverse_lazy('post:show')

class Update(UpdateView):
	"""docstring for MascotaCreate"""
	model=Post
	form_class=PostForm
	template_name='post/view.html'
	success_url=reverse_lazy('post:show')

class Delete(DeleteView):
	"""docstring for MascotaDelete"""
	model=Post
	template_name='post/delete.html'
	success_url=reverse_lazy('post:show')
	
class EncuentroCalendario(TemplateView):
	"""docstring for Encuentro"""
	template_name='encuentros.html'
	

class EncuentroAPI(View):
	"""docstring for Encuentro"""
	template_name='encuentro.html'

apps/landing/views.py
from django.shortcuts import render
from apps.core.models import Post, Club
from django.views.generic import TemplateView
from apps.core.models import Club, Post
from django.http import JsonResponse
from pdb import set_trace
# Create your views here.


class Index(TemplateView):
	template_name="landing/index.html"

	def get(self, *args, **kwargs):
		# self.periodo = self.request.GET.get('periodo', settings.PERIODO_POR_DEFECTO)
		return super().get(*args, **kwargs)

	def get_context_data(self, *args, **kwargs):
		data = super().get_context_data(*args, **kwargs)
		data['club'] = Club.objects.filter(pk=1)
		data['post'] = Post.objects.all().order_by('id')
		return data


def club_info(request):
	club=Club.objects.all().order_by('id')
	context={'club':club}
	return render(request, 'landing/club_info.html', context)

apps/user/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
# Create your views here.

class RegisterUser(CreateView):
	"""docstring for RegisterUser"""
	model=User
	template_name='user/create.html'
	form_class=UserCreationForm
	success_url=reverse_lazy('mascota:mascota_list')

templates/base/base_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{%block title%}{%endblock%}</title>
  <link rel="stylesheet" href="{% static 'style-login/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'style-login/vendors/base/vendor.bundle.base.css' %}">
  <link rel="stylesheet" href="{% static 'style-login/css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'landing/img/logo_1.jpg' %}" />
</head>

<body>
  <div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
      <div class="content-wrapper d-flex align-items-stretch auth auth-img-bg">
        <div class="row flex-grow">
          <div class="col-lg-6 d-flex align-items-center justify-content-center">
            <div class="auth-form-transparent text-left p-3">
              {% block body %}
                  {% block logo %}{% endblock logo %}
                  <h4>Welcome back!</h4>
                  <h6 class="font-weight-light">Happy to see you again!</h6>
                  {% block login_form %}{% endblock login_form %}
              {% endblock %}
            </div>
          </div>
          <div class="col-lg-6 login-half-bg d-flex flex-row">
            <p class="text-white font-weight-medium text-center flex-grow align-self-end">Copyright &copy; {% now "Y" %}</p>
          </div>
        </div>
      </div>
      <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->
  <!-- base:js -->
  <script src="{% static 'style-login/vendors/base/vendor.bundle.base.js'%}"></script>
  <script src="{% static 'style-login/js/template.js'%}"></script>
</body>

</html>

templates/encuentros.html
{% extends "adminlte/base.html" %}
{% load i18n static %}
{% load admin_menu %}

{% block extrastyle %}
{{ block.super }}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'admin/css/dashboard.css' %}" /> -->
{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}
{% if not is_popup %}
{% block breadcrumbs %}
<div class="row mb-2">
    <div class="col-sm-4">
        <h2>{{title}}</h2>
    </div>
    <div class="col-sm-8">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></li>
            {% for app in app_list %}
            <li class="breadcrumb-item active">{{ app.name }}</li>
            {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}
{% endif %}


{% block content %}
<div id="content-main" class="container-fluid">
    <div class="row">
        {% if app_list %}
        <h1>hola</h1>
        {% for app in app_list %}

        <div class="card card-widget col-md-12">
            <div class="card-header ">
                <h3 class="card-title"><a href="{{ app.app_url }}" class="nav-link"
                        title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">{{ app.name }}</a>
                </h3>

                <div class="card-tools pull-right">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="card-body">
                <div class="row">
                    {% for model in app.models %}

                    <div class="col-md-4 col-sm-6 model-box">

                        <div class="info-box bg-secondary">
                                
                            <span class="info-box-icon">
                                <a href="{{ model.admin_url }}">{% autoescape off %}{% icon %}{% endautoescape %}</a>
                            </span>
                        
                            <div class="info-box-content">
                                <a href="{{ model.admin_url }}">
                                    <span class="info-box-text text-light">{{ model.name }}</span>
                                </a>
                                {% if model.add_url %}
                                <a href="{{ model.add_url }}" class="btn btn-default btn-xs btn-block"><i
                                        class="fa fa-plus"></i> {%trans 'Add' %}</a>
                                {% endif %}
                                {% if model.admin_url %}
                                <a href="{{ model.admin_url }}" class="btn btn-warning btn-xs btn-block"><i
                                        class="fa fa-pencil"></i>
                                    {%trans 'Change' %}</a>
                                {% endif %}
                            </div>

                            <!-- /.info-box-content -->
                        </div>
                    </div>
                    {% endfor %}
                </div>



                {% comment %}<div class="app-{{ app.app_label }} module">
                    <table class="table table-hover table-striped">
                        <caption>
                            <a href="{{ app.app_url }}" class="section"
                                title="{% blocktrans with name=app.name %}Models in the {{ name }} application{% endblocktrans %}">{{ app.name }}</a>
                        </caption>
                        {% for model in app.models %}
                        <tr class="model-{{ model.object_name|lower }}">
                            {% if model.admin_url %}
                            <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
                            {% else %}
                            <th scope="row">{{ model.name }}</th>
                            {% endif %}

                            {% if model.add_url %}
                            <td><a href="{{ model.add_url }}" class="btn btn-success btn-xs"><i class="fa fa-plus"></i>
                                    {% trans 'Add' %}</a></td>
                            {% else %}
                            <td>&nbsp;</td>
                            {% endif %}

                            {% if model.admin_url %}
                            <td><a href="{{ model.admin_url }}" class="btn btn-warning btn-xs"><i
                                        class="fa fa-pencil"></i>
                                    {% trans 'Change' %}</a></td>
                            {% else %}
                            <td>&nbsp;</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                    </table>
                </div>{% endcomment %}
            </div>
        </div>
                {% endfor %}
            
                {% else %}
                <p>{% trans "You don't have permission to edit anything." %}</p>
                {% endif %}
                <!-- /.box-body -->

</div>

{% endblock %}

templates/landing/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="Verport" content="width=device-width, initial-scale=1.0">
  <title>Inicio - Nombre del Club</title>
    {% include "landing/lib/_style_css.html" %}
</head>

<body>
    {% include "landing/lib/_header.html"  %}
    <!-- header-end -->

    {% block "content" %}{% endblock %}
  
    <!-- footer start -->
    {% include "landing/lib/_footer.html" %}
    <!--/ footer end  -->

    <!-- JS here -->
    {% include "landing/lib/_style_js.html" %}
</body>
</html>

templates/landing/lib/_footer.html
{% load static %}
<!-- ***** Contact Us Area Start ***** -->
<footer class="footer">
    <div class="footer_top" style="padding-top:2rem">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4"></div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer_logo wow fadeInRight" style="text-align:center!important;margin-bottom:2rem;padding-bottom:1rem!important;width:10rem;height:10rem;margin:0px auto" data-wow-duration="1s" data-wow-delay=".3s">
                        <a href="index.html">
                            <img style="width:100%;height:100%;border-radius:50%;text-align:center;margin:0px auto" src="{% static '/landing/img/logo_1.jpg' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="col-lg-4"></div>
            </div>
            <div class="row align-items-center" style="margin-bottom:2rem">
                <div class="col-xl-4 col-lg-4 col-md-4 wow fadeInRight">
                    <h3 class="text-center text-white">Pagina</h3>
                    <hr style="background-color:white; width:2em;">
                    <ul class="text-white">
                        <li><a class="text-white" href="{% url 'landing:index' %}">Inicio</a></li>
                        <li><a class="text-white" href="{% url 'landing:club_info' %}">El Club</a></li>
                        <li><a class='text-white' href="#">Plantilla</a></li>
                        <li><a class='text-white' href="#">Calendario</a></li>
                        <li><a class='text-white' href="#">Perfiles</a></li>
                        <li><a class='text-white' href="#">Contactos</a></li>
                    </ul>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-4 wow fadeInRight">
                    <h3 class="text-center text-white">Club</h3>
                    <hr style="background-color:white; width:2em;">
                    <ul class="text-white">
                        <li>a</li>
                        <li>a</li>
                        <li>a</li>
                        <li>a</li>
                        <li>a</li>
                    </ul>
                </div>
                <div class="col-xl-4 col-lg-4 col-md-4 wow fadeInRight">
                    <h3 class="text-center text-white">Dirección</h3>
                    <hr style="background-color:white; width:2em;">
                    <ul class="text-white">
                        <li>Nombre{{ club.nombre | default_if_none:"Nombre" }}</li>
                        <li>Nombre{{ club.nombre }}</li>
                        <li>a</li>
                        <li>a</li>
                        <li>a</li>
                    </ul>
                </div>
            </div>
            <div class="row align-items-center">
                <div class="col-lg-4"></div>
                <div class="col-lg-4 col-md-12">
                    <div class="socail_links" style="text-align: center!important;">
                        <ul>
                            <li><a class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s" href="#"> <i class="fa fa-facebook"></i> </a></li>
                            <li><a class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".4s" href="#"> <i class="fa fa-twitter"></i> </a></li>
                            <li><a class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s" href="#"> <i class="fa fa-instagram"></i> </a></li>
                            <li><a class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".6s" href="#"> <i class="fa fa-google-plus"></i> </a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4"></div>
            </div>
        </div>
    </div>
    <div class="copy-right_text">
        <div class="container">
            <div class="footer_border"></div>
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.3s">Copyright &copy;{% now 'Y' %}</p>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ***** Footer Area Start ***** -->

templates/landing/lib/_header.html
{% load static %}
<header>
    <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
            <div class="container-fluid p-0">
                <div class="row align-items-center no-gutters">
                    <div class="col-xl-2 col-lg-2">
                        <div class="logo-img">
                            <a href="index.html">
                                <div style="width:5rem;height:5rem">
                                  <img style="border-radius:50%;width:100%;height:100%" src="{% static '/landing/img/logo_1.jpg' %}" alt="">
                              </div>
                          </a>
                      </div>
                  </div>
                  <div class="col-xl-8 col-lg-8">
                    <div class="main-menu  d-none d-lg-block text-center">
                        <nav>
                            <ul id="navigation">
                                <li><a class="" href="{% url 'landing:index' %}">Inicio</a></li>
                                <li><a class="" href="{% url 'landing:club_info' %}">El Club</a></li>
                                <li><a class="" href="#">Plantilla</a></li>
                                <li><a class="" href="#">Calendario</a></li>
                                <li><a class="" href="#">Perfiles</a></li>
                                <li><a class="" href="#">Contactos</a></li>
                                <!-- <li><a href="#">paginas <i class="ti-angle-down"></i></a>
                                    <ul class="submenu">
                                        <li><a href="#">random</a></li>
                                        <li><a href="#">random</a></li>
                                        <li><a href="#">random</a></li>
                                    </ul>
                                </li> -->
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-2 d-none d-lg-block">
                    <div class="log_chat_area d-flex align-items-end">
                        <a href="#" data-scroll-nav="0" class="say_hi">Say Hello</a>
                    </div>
                </div>
                <div class="col-12">
                    <div class="mobile_menu d-block d-lg-none"></div>
                </div>
            </div>
        </div>
    </div>
</div>
</header>
<!-- slider_area_start -->
    <div class="slider_area">
        <div class="single_slider  d-flex align-items-center slider_bg_1 overlay">
            <div class="container">
                <div class="row align-items-center justify-content-start">
                    <div class="col-lg-10 col-md-10">
                        <div class="slider_text">
                            <h3 class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".1s">
                                Lorem ipsum dolor, sit amet, consectetur adipisicing elit. 
                            </h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider_area_end -->

templates/landing/lib/_style_css.html
{% load static %}
<link rel="stylesheet" href="{% static '/landing/startup/css/bootstrap.min.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/owl.carousel.min.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/magnific-popup.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/font-awesome.min.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/themify-icons.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/nice-select.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/flaticon.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/gijgo.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/animate.min.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/slick.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/slicknav.css'%}">
<link rel="stylesheet" href="{% static '/landing/startup/css/style.css'%}">

templates/landing/lib/_style_js.html
{% load static%} 
<script src="{% static '/landing/startup/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<script src="{% static '/landing/startup/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static '/landing/startup/js/popper.min.js' %}"></script>
<script src="{% static '/landing/startup/js/bootstrap.min.js' %}"></script>
<script src="{% static '/landing/startup/js/owl.carousel.min.js' %}"></script>
<script src="{% static '/landing/startup/js/isotope.pkgd.min.js' %}"></script>
<script src="{% static '/landing/startup/js/ajax-form.js' %}"></script>
<script src="{% static '/landing/startup/js/waypoints.min.js' %}"></script>
<script src="{% static '/landing/startup/js/jquery.counterup.min.js' %}"></script>
<script src="{% static '/landing/startup/js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static '/landing/startup/js/scrollIt.js' %}"></script>
<script src="{% static '/landing/startup/js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static '/landing/startup/js/wow.min.js' %}"></script>
<script src="{% static '/landing/startup/js/nice-select.min.js' %}"></script>
<script src="{% static '/landing/startup/js/jquery.slicknav.min.js' %}"></script>
<script src="{% static '/landing/startup/js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static '/landing/startup/js/plugins.js' %}"></script>
<script src="{% static '/landing/startup/js/gijgo.min.js' %}"></script>

<!--contact js-->
<script src="{% static '/landing/startup/js/contact.js' %}"></script>
<script src="{% static '/landing/startup/js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static '/landing/startup/js/jquery.form.js' %}"></script>
<script src="{% static '/landing/startup/js/jquery.validate.min.js' %}"></script>
<script src="{% static '/landing/startup/js/mail-script.js' %}"></script>

<script src="{% static '/landing/startup/js/main.js' %}"></script>